### ISSUE TITLE
Needs way to store data and the ability to clear data after certain period

### ISSUE THREAD

**Issue by conraddev** [conraddev/ncjs-mentorship-helpdesk#5]
The app needs a way to store data and the ability to clear data after certain period. Thinking mongo, but maybe firebase?

**Comment by andreas-groos** [comment]
I would like to use firebase for us to learn it, seems  a good thing to have some knowledge. I tried to make use the /ask route (Help.js? hello consistency) into a controlled component but the semantic dropdown didn't play along. Might do a quick sketch today of it in a plain/seperate component just for testing purposes. I can upload the branch just for you to see the issue.
